### ISSUE TITLE
Kairos High Council Meeting 01 Agenda

### ISSUE THREAD

**Issue by Alexintosh** [KairosProject/Pm#1]
# Kairos High Counci Agenda

### Meeting Duration 1.5 hours

[Call Link](https://appear.in/kairoscouncil)
## Agenda

1. Introducing [agile](https://www.slideshare.net/TanaLinback/agile-101-56280748)
2. Responsibilities & Assignments 
3. CryptoSwag Status Report
4. Sprint Planning
5. Discussion on participating in [NEO](https://neo.org/competition.html) / [ETH](https://www.reddit.com/r/ethdev/comments/75itou/ethdev_hackathon_dates_and_rules_sign_up_here_to/) Competitions
6. High Council updates.

Please provide comments to add or correct agenda topics.

**Comment by dimarconicola** [comment]
Maybe we could provide a short list of project we could vote? Or are we considering LoF only?

**Comment by Alexintosh** [comment]
Do we have some links to do that?  Like gDocs or similar?

**Comment by dimarconicola** [comment]
@Alexintosh  I am preparing it. It's currently in italian, should I translate it in english?

**Comment by dimarconicola** [comment]
Doing it in english, it's easier for future purposes.

**Comment by dimarconicola** [comment]
Please refer to this document
https://github.com/dimarconicola/Projects_Proposals/blob/patch-1/Informal%20List%20of%20Projects

**Comment by dimarconicola** [comment]
@Alexintosh can we please specify the channel? Is it skype?

**Comment by Alexintosh** [comment]
Added to the issue

**Comment by dimarconicola** [comment]
24th Nov 2017
Kairos Council
https://appear.in/cryptomafia
Participants: @dimarconicola @Alexintosh @gabcava @alearrigo 

#Intro about Github Docs and Agile
PM stack: Github + Slack
Issue:
tag (i.e. new feature, bug)
assignment (who's working on)
priority / time

#Projects List
How to choose:
- development resources (Only Alessio at the moment)
- solidity?
- no multi contracts project
- standalone projects 
- platform: choose only one. is it easy to enter as a project? (NEO is expensive)
- hackaton: mostly on ethereum. microsoft+NEO

#Reading and short discussion about the list.

#Projects to start with:
Plugin CoinPayment
Coupon
Microservices that can interact with each-other
i.e Post Mortem as a micro service

E-sport betting
Post mortem message
Leap of faith
Coinpayments

##New Projects to add
- https://www.rocketpool.net/ Is it feasible for us? We need 32eth
- Auto Storiche come asset. Ente garante + case d'aste di auto storiche. Modello realestate.
- Porting agency that brings existing projects on blockchain
- Exchanger
- Transaction rating linked to an address

#Output
- Ethereum is the platform!
- Leap of faith is the next project!
- Create Cryptoswag Backlog
- Postmortem / E-betting Project proposal
- Nico and Ale: project management on Github
